In [1]:
import urllib.request
import pandas as pd
import json

base_url = "https://www.donneesquebec.ca/recherche/api/3/action/datastore_search"
resource_id = "c6640a54-bc4b-43ec-864e-6c325dce61bc"
filters = json.dumps({"NOM_MUNCP_GDUNO_ORGNS": "Montréal"})
# filters = {}
query_params = urllib.parse.urlencode(
    {"resource_id": resource_id, "filters": filters, "limit": 5000}
)
url = f"{base_url}?{query_params}"
with urllib.request.urlopen(url) as response:
    data_dict = json.loads(response.read().decode('utf-8'))
df = pd.DataFrame(data_dict["result"]["records"])

df

,_id,DT_MAJ_GDUNO,COMBINE_NUO_NUI,CD_ORGNS,NOM_COURT_ORGNS,NOM_OFFCL_ORGNS,ADRS_GEO_L1_GDUNO_ORGNS,ADRS_GEO_L2_GDUNO_ORGNS,CD_POSTL_GDUNO_ORGNS,CD_MUNCP_GDUNO_ORGNS,...,COORD_Y_LL84_IMM,ORDRE_ENS,CD_CS,TYPE_CS,STYLE_CART,NOM_MUNCP,NOM_MRC,NOM_REG_ADM,NOM_CEP,NOM_CS
0,48,None,None,762132,École François-de-Laval,École François-de-Laval,"12050, avenue Bois-de-Boulogne",NaN,H3M2X9,66023,...,45.542872,Préscolaire - Primaire,762000,Franco,4_OrgImm_Franco_presc_prim,Montréal,Montréal,Montréal,Acadie,Centre de services scolaire de Montréal
1,156,None,None,763405,CFP Léonard-De Vinci,Centre de formation professionnelle Léonard-De...,"2405, boulevard Thimens",NaN,H4R1T4,66023,...,45.50977,Formation professionnelle,763000,Franco,8_OrgImm_Franco_Fp,Montréal,Montréal,Montréal,Nelligan,Centre de services scolaire Marguerite-Bourgeoys
2,157,None,None,763245,École de l'Altitude,École de l'Altitude,"5060, boulevard des Sources",NaN,H8Y3E4,66023,...,45.50977,Secondaire,763000,Franco,3_OrgImm_Franco_secondaire,Montréal,Montréal,Montréal,Nelligan,Centre de services scolaire Marguerite-Bourgeoys
3,237,None,None,887253,École Centre Mackay,École Centre Mackay,"6333, rue de Terrebonne",NaN,H4B1A8,66023,...,45.468946,Préscolaire - Primaire - Secondaire,887000,Anglo,5_OrgImm_Anglo_presc_prim_sec,Montréal,Montréal,Montréal,Notre-Dame-de-Grâce,Commission scolaire English-Montréal
4,238,None,None,887256,École Philip E. Layton,École Philip E. Layton,"6333, rue de Terrebonne",NaN,H4B1A8,66023,...,45.468946,Préscolaire - Primaire - Secondaire,887000,Anglo,5_OrgImm_Anglo_presc_prim_sec,Montréal,Montréal,Montréal,Notre-Dame-de-Grâce,Commission scolaire English-Montréal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
566,5403,None,None,888310,Centre de formation des adultes West-Isl,Centre de formation des adultes West-Island,"13700, boulevard de Pierrefonds",NaN,H9A1A7,66023,...,45.49249,Éducation aux adultes,888000,Anglo,9_OrgImm_Anglo_Adu,Montréal,Montréal,Montréal,Robert-Baldwin,Commission scolaire Lester-B.-Pearson
567,5415,None,None,888401,Centre PACC-Formation professionnelle,Centre de formation des adultes et de formatio...,"8310, rue George",NaN,H8P1E5,66023,...,45.451981,Formation professionnelle,888000,Anglo,8_OrgImm_Anglo_Fp,Pointe-Claire,Montréal,Montréal,Jacques-Cartier,Commission scolaire Lester-B.-Pearson
568,5416,None,None,888401,Centre PACC-Formation professionnelle,Centre de formation des adultes et de formatio...,"8310, rue George",NaN,H8P1E5,66023,...,45.4222,Formation professionnelle,888000,Anglo,8_OrgImm_Anglo_Fp,Montréal,Montréal,Montréal,Marguerite-Bourgeoys,Commission scolaire Lester-B.-Pearson
569,5417,None,None,888403,Centre de formation prof. West-Island,Centre de formation professionnelle West-Island,"13700, boulevard de Pierrefonds",NaN,H9A1A7,66023,...,45.49249,Formation professionnelle,888000,Anglo,8_OrgImm_Anglo_Fp,Montréal,Montréal,Montréal,Robert-Baldwin,Commission scolaire Lester-B.-Pearson
570,5419,None,None,888408,Centre de formation de métiers Verdun,Centre de formation des métiers de Verdun,6050 boulevard Champlain,NaN,H4H1A5,66023,...,45.448273,Formation professionnelle,888000,Anglo,8_OrgImm_Anglo_Fp,Montréal,Montréal,Montréal,Verdun,Commission scolaire Lester-B.-Pearson

In [5]:
from borough_identifier import BoroughIdentifier

bi = BoroughIdentifier()
x = df['COORD_X_LL84_IMM']
y = df['COORD_Y_LL84_IMM']
# X and Y are switched
df['borough'] = df.apply(lambda row: bi.match_WSG84_to_borough(longitude_x=row['COORD_X_LL84_IMM'], latitude_y=row['COORD_Y_LL84_IMM']), axis=1)

In [7]:
df = df.groupby(['NOM_OFFCL_ORGNS', 'borough'], as_index=False).agg(lambda x: ', '.join(x.dropna().astype(str).unique()))

In [8]:
df

,NOM_OFFCL_ORGNS,borough,_id,DT_MAJ_GDUNO,COMBINE_NUO_NUI,CD_ORGNS,NOM_COURT_ORGNS,ADRS_GEO_L1_GDUNO_ORGNS,ADRS_GEO_L2_GDUNO_ORGNS,CD_POSTL_GDUNO_ORGNS,...,COORD_Y_LL84_IMM,ORDRE_ENS,CD_CS,TYPE_CS,STYLE_CART,NOM_MUNCP,NOM_MRC,NOM_REG_ADM,NOM_CEP,NOM_CS
0,Académie De Roberval,Villeray-Saint-Michel-Parc-Extension,"1841, 1842",,,762267,Académie De Roberval,"1275, rue Jarry Est",,H2P1W9,...,"45.550206, 45.544996",Secondaire,762000,Franco,3_OrgImm_Franco_secondaire,Montréal,Montréal,Montréal,Laurier-Dorion,Centre de services scolaire de Montréal
1,Académie Dunton,Mercier-Hochelaga-Maisonneuve,1829,,,762253,Académie Dunton,"5555, rue De Boucherville",,H1K4B6,...,45.596233,Secondaire,762000,Franco,3_OrgImm_Franco_secondaire,Montréal,Montréal,Montréal,Camille-Laurin,Centre de services scolaire de Montréal
2,Académie Internationale Marymount,Côte-des-Neiges-Notre-Dame-de-Grâce,5303,,,887108,Académie Internationale Marymount,"5100, chemin de la Côte-Saint-Luc",,H3W2G9,...,45.482167,Secondaire,887000,Anglo,3_OrgImm_Anglo_secondaire,Montréal,Montréal,Montréal,Notre-Dame-de-Grâce,Commission scolaire English-Montréal
3,Académie John Caboto,Ahuntsic-Cartierville,5270,,,887019,Académie John Caboto,"8955, rue Meunier",,H2N1W3,...,45.539362,Préscolaire - Primaire,887000,Anglo,4_OrgImm_Anglo_presc_prim,Montréal,Montréal,Montréal,Acadie,Commission scolaire English-Montréal
4,Académie Leonardo-da-Vinci,Rivière-des-Prairies-Pointe-aux-Trembles,5271,,,887021,Académie Leonardo-da-Vinci,"12025, rue André Dumas",,H1E4G2,...,45.637732,Préscolaire - Primaire,887000,Anglo,4_OrgImm_Anglo_presc_prim,Montréal,Montréal,Montréal,LaFontaine,Commission scolaire English-Montréal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
419,École Édouard-Laurin,Saint-Laurent,1911,,,763007,École Édouard-Laurin,"1085, rue Tassé",,H4L1P7,...,45.521308,Préscolaire - Primaire,763000,Franco,4_OrgImm_Franco_presc_prim,Montréal,Montréal,Montréal,Acadie,Centre de services scolaire Marguerite-Bourgeoys
420,École Édouard-Montpetit,Mercier-Hochelaga-Maisonneuve,1831,,,762256,École Édouard-Montpetit,"6200, avenue Pierre-De Coubertin",,H1N1S4,...,45.576505,Secondaire,762000,Franco,3_OrgImm_Franco_secondaire,Montréal,Montréal,Montréal,Camille-Laurin,Centre de services scolaire de Montréal
421,École Élan,Le Plateau-Mont-Royal,1717,,,762081,École Élan,"3450, avenue De Lorimier",,H2K3X6,...,45.53074,Préscolaire - Primaire,762000,Franco,4_OrgImm_Franco_presc_prim,Montréal,Montréal,Montréal,Sainte-Marie–Saint-Jacques,Centre de services scolaire de Montréal
422,École Étoile filante,Côte-des-Neiges-Notre-Dame-de-Grâce,1791,,,762158,École Étoile filante,"5619, chemin de la Côte-Saint-Antoine",,H4A1R5,...,45.472627,Primaire,762000,Franco,2_OrgImm_Franco_primaire,Montréal,Montréal,Montréal,Notre-Dame-de-Grâce,Centre de services scolaire de Montréal
423,École Île-des-Soeurs,Verdun,1946,,,763104,École Île-des-Soeurs,"530, rue de Gaspé",,H3E1E7,...,45.456886,Préscolaire - Primaire,763000,Franco,4_OrgImm_Franco_presc_prim,Montréal,Montréal,Montréal,Verdun,Centre de services scolaire Marguerite-Bourgeoys

In [9]:
df['borough'].unique()

<StringArray>
[    'Villeray-Saint-Michel-Parc-Extension',
            'Mercier-Hochelaga-Maisonneuve',
      'Côte-des-Neiges-Notre-Dame-de-Grâce',
                    'Ahuntsic-Cartierville',
 'Rivière-des-Prairies-Pointe-aux-Trembles',
                            'Montréal-Nord',
                'Rosemont-La Petite-Patrie',
                    'Le Plateau-Mont-Royal',
                              'Ville-Marie',
                             'Le Sud-Ouest',
                            'Saint-Léonard',
                                  'LaSalle',
                                   'Verdun',
                                'Outremont',
                            'Saint-Laurent',
                                  'Lachine',
                                    'Anjou',
                      'Pierrefonds-Roxboro',
            'L'Île-Bizard-Sainte-Geneviève']
Length: 19, dtype: str

In [10]:
for brgh in df['borough'].unique():
    schools = len(df[df['borough']==brgh])
    print(f"{brgh}: {schools} schools")

Villeray-Saint-Michel-Parc-Extension: 41 schools
Mercier-Hochelaga-Maisonneuve: 39 schools
Côte-des-Neiges-Notre-Dame-de-Grâce: 38 schools
Ahuntsic-Cartierville: 30 schools
Rivière-des-Prairies-Pointe-aux-Trembles: 28 schools
Montréal-Nord: 23 schools
Rosemont-La Petite-Patrie: 37 schools
Le Plateau-Mont-Royal: 25 schools
Ville-Marie: 14 schools
Le Sud-Ouest: 24 schools
Saint-Léonard: 14 schools
LaSalle: 25 schools
Verdun: 20 schools
Outremont: 7 schools
Saint-Laurent: 17 schools
Lachine: 15 schools
Anjou: 9 schools
Pierrefonds-Roxboro: 15 schools
L'Île-Bizard-Sainte-Geneviève: 3 schools

In [11]:
total_pop = {'Côte-des-Neiges-Notre-Dame-de-Grâce': 170583, # according to https://ville.montreal.qc.ca/pls/portal/docs/PAGE/MTL_STATS_FR/MEDIA/DOCUMENTS/CARTE_POPULATION%20ET%20SUPERFICIE%202021.PDF
'Ville-Marie': 104944,
'Montréal-Nord': 88471,
'Mercier-Hochelaga-Maisonneuve': 140627,
'Pierrefonds-Roxboro': 70382,
'Rivière-des-Prairies-Pointe-aux-Trembles': 107941,
'Lachine': 46428,
'Saint-Laurent': 102104,
'Rosemont-La Petite-Patrie': 141813,
'Ahuntsic-Cartierville': 135336,
'Le Plateau-Mont-Royal': 105813,
'Verdun': 70377,
'LaSalle': 82235,
'Villeray-Saint-Michel-Parc-Extension': 145090,
'Anjou': 43243,
'Le Sud-Ouest': 84553,
'L\'Île-Bizard-Sainte-Geneviève': 18885,
'Saint-Léonard': 79495,
'Outremont': 24629}

for brgh in df['borough'].unique():
    schools = len(df[df['borough']==brgh])
    print(f"{brgh}: {((total_pop[brgh] / schools)):.2f} people per school.")

Villeray-Saint-Michel-Parc-Extension: 3538.78 people per school.
Mercier-Hochelaga-Maisonneuve: 3605.82 people per school.
Côte-des-Neiges-Notre-Dame-de-Grâce: 4489.03 people per school.
Ahuntsic-Cartierville: 4511.20 people per school.
Rivière-des-Prairies-Pointe-aux-Trembles: 3855.04 people per school.
Montréal-Nord: 3846.57 people per school.
Rosemont-La Petite-Patrie: 3832.78 people per school.
Le Plateau-Mont-Royal: 4232.52 people per school.
Ville-Marie: 7496.00 people per school.
Le Sud-Ouest: 3523.04 people per school.
Saint-Léonard: 5678.21 people per school.
LaSalle: 3289.40 people per school.
Verdun: 3518.85 people per school.
Outremont: 3518.43 people per school.
Saint-Laurent: 6006.12 people per school.
Lachine: 3095.20 people per school.
Anjou: 4804.78 people per school.
Pierrefonds-Roxboro: 4692.13 people per school.
L'Île-Bizard-Sainte-Geneviève: 6295.00 people per school.